// Code generated by sqlc-fixture plugin for SQLc. DO NOT EDIT.

package fixture

import (
	"context"
	"github.com/go-modulus/demo/internal/blog/storage"
	uuid "github.com/gofrs/uuid"
	null "gopkg.in/guregu/null.v4"
	"testing"
	"time"
)

type BlogPostFixture struct {
	entity storage.BlogPost
	db     storage.DBTX
}

func NewBlogPostFixture(db storage.DBTX, defaultEntity storage.BlogPost) *BlogPostFixture {
	return &BlogPostFixture{
		db:     db,
		entity: defaultEntity,
	}
}

func (f *BlogPostFixture) ID(iD uuid.UUID) *BlogPostFixture {
	c := f.clone()
	c.entity.ID = iD
	return c
}

func (f *BlogPostFixture) Title(title string) *BlogPostFixture {
	c := f.clone()
	c.entity.Title = title
	return c
}

func (f *BlogPostFixture) Preview(preview string) *BlogPostFixture {
	c := f.clone()
	c.entity.Preview = preview
	return c
}

func (f *BlogPostFixture) Content(content string) *BlogPostFixture {
	c := f.clone()
	c.entity.Content = content
	return c
}

func (f *BlogPostFixture) Status(status storage.BlogPostStatus) *BlogPostFixture {
	c := f.clone()
	c.entity.Status = status
	return c
}

func (f *BlogPostFixture) CreatedAt(createdAt time.Time) *BlogPostFixture {
	c := f.clone()
	c.entity.CreatedAt = createdAt
	return c
}

func (f *BlogPostFixture) UpdatedAt(updatedAt time.Time) *BlogPostFixture {
	c := f.clone()
	c.entity.UpdatedAt = updatedAt
	return c
}

func (f *BlogPostFixture) PublishedAt(publishedAt null.Time) *BlogPostFixture {
	c := f.clone()
	c.entity.PublishedAt = publishedAt
	return c
}

func (f *BlogPostFixture) DeletedAt(deletedAt null.Time) *BlogPostFixture {
	c := f.clone()
	c.entity.DeletedAt = deletedAt
	return c
}

func (f *BlogPostFixture) clone() *BlogPostFixture {
	return &BlogPostFixture{
		db:     f.db,
		entity: f.entity,
	}
}

func (f *BlogPostFixture) save(ctx context.Context) error {
	query := `INSERT INTO "blog"."post"
            ("id", "title", "preview", "content", "status", "created_at", "updated_at", "published_at", "deleted_at")
            VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
            RETURNING "id", "title", "preview", "content", "status", "created_at", "updated_at", "published_at", "deleted_at"
        `
	row := f.db.QueryRow(ctx, query,
		f.entity.ID,
		f.entity.Title,
		f.entity.Preview,
		f.entity.Content,
		f.entity.Status,
		f.entity.CreatedAt,
		f.entity.UpdatedAt,
		f.entity.PublishedAt,
		f.entity.DeletedAt,
	)
	err := row.Scan(
		&f.entity.ID,
		&f.entity.Title,
		&f.entity.Preview,
		&f.entity.Content,
		&f.entity.Status,
		&f.entity.CreatedAt,
		&f.entity.UpdatedAt,
		&f.entity.PublishedAt,
		&f.entity.DeletedAt,
	)
	return err
}

func (f *BlogPostFixture) GetEntity() storage.BlogPost {
	return f.entity
}

func (f *BlogPostFixture) Create(tb testing.TB) *BlogPostFixture {
	err := f.save(context.Background())
	if err != nil {
		tb.Fatalf("failed to create BlogPost: %v", err)
	}
	f.Cleanup(tb)
	c := f.clone()
	return c
}

// Cleanup calls testing.TB.Cleanup() function with providing a callback inside it.
// This callback will delete a record from the table by primary key when test will be finished.
func (f *BlogPostFixture) Cleanup(tb testing.TB) *BlogPostFixture {
	tb.Cleanup(
		func() {
			query := `DELETE FROM "blog"."post" WHERE id = $1`
			_, err := f.db.Exec(context.Background(), query, f.entity.ID)

			if err != nil {
				tb.Fatalf("failed to cleanup BlogPost: %v", err)
			}
		})

	return f
}

func (f *BlogPostFixture) PullUpdates(tb testing.TB) *BlogPostFixture {
	c := f.clone()
	ctx := context.Background()
	query := `SELECT "id", "title", "preview", "content", "status", "created_at", "updated_at", "published_at", "deleted_at" FROM "blog"."post" WHERE id = $1`
	row := f.db.QueryRow(ctx, query,
		c.entity.ID,
	)

	err := row.Scan(
		&c.entity.ID,
		&c.entity.Title,
		&c.entity.Preview,
		&c.entity.Content,
		&c.entity.Status,
		&c.entity.CreatedAt,
		&c.entity.UpdatedAt,
		&c.entity.PublishedAt,
		&c.entity.DeletedAt,
	)
	if err != nil {
		tb.Fatalf("failed to actualize data BlogPost: %v", err)
	}
	return c
}

func (f *BlogPostFixture) PushUpdates(tb testing.TB) *BlogPostFixture {
	c := f.clone()
	query := `
        UPDATE "blog"."post" SET 
            "title" = $2,
            "preview" = $3,
            "content" = $4,
            "status" = $5,
            "created_at" = $6,
            "updated_at" = $7,
            "published_at" = $8,
            "deleted_at" = $9
        WHERE "id" = $1
        `
	_, err := f.db.Exec(
		context.Background(),
		query,
		f.entity.ID,
		f.entity.Title,
		f.entity.Preview,
		f.entity.Content,
		f.entity.Status,
		f.entity.CreatedAt,
		f.entity.UpdatedAt,
		f.entity.PublishedAt,
		f.entity.DeletedAt,
	)
	if err != nil {
		tb.Fatalf("failed to push the data BlogPost: %v", err)
	}
	return c
}
