// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: user.sql

package storage

import (
	"context"
	"time"

	uuid "github.com/gofrs/uuid"
)

const createUser = `-- name: CreateUser :one
insert into "user"."user" (id, name, email, registered_at, settings, contacts)
values ($1, $2, $3, now(), null, null) RETURNING id, name, email, registered_at, settings, contacts
`

type CreateUserParams struct {
	ID    uuid.UUID `db:"id" json:"id"`
	Name  string    `db:"name" json:"name"`
	Email string    `db:"email" json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Name, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.RegisteredAt,
		&i.Settings,
		&i.Contacts,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
delete from "user"."user" where id = $1::uuid
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteUserByEmail = `-- name: DeleteUserByEmail :exec
delete from "user"."user" where email = $1::text
`

func (q *Queries) DeleteUserByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteUserByEmail, email)
	return err
}

const getNewerUsers = `-- name: GetNewerUsers :many
select id, name, email, registered_at, settings, contacts from "user"."user" order by "user".registered_at DESC LIMIT $1
`

func (q *Queries) GetNewerUsers(ctx context.Context, count int32) ([]User, error) {
	rows, err := q.db.Query(ctx, getNewerUsers, count)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.RegisteredAt,
			&i.Settings,
			&i.Contacts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
select id, name, email, registered_at, settings, contacts from "user"."user" where id = $1::uuid LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.RegisteredAt,
		&i.Settings,
		&i.Contacts,
	)
	return i, err
}

const getUsersAfterCursor = `-- name: GetUsersAfterCursor :many
select id, name, email, registered_at, settings, contacts from "user"."user"
where
        registered_at < $1 OR
    (registered_at = $1 AND id < $2::uuid)
order by "user".registered_at DESC, "user".id DESC LIMIT $3
`

type GetUsersAfterCursorParams struct {
	RegisteredAt time.Time `db:"registered_at" json:"registeredAt"`
	ID           uuid.UUID `db:"id" json:"id"`
	Count        int32     `db:"count" json:"count"`
}

func (q *Queries) GetUsersAfterCursor(ctx context.Context, arg GetUsersAfterCursorParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersAfterCursor, arg.RegisteredAt, arg.ID, arg.Count)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.RegisteredAt,
			&i.Settings,
			&i.Contacts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByIds = `-- name: GetUsersByIds :many
select id, name, email, registered_at, settings, contacts from "user"."user" WHERE id = ANY ($1::uuid[])
`

func (q *Queries) GetUsersByIds(ctx context.Context, ids []uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByIds, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.RegisteredAt,
			&i.Settings,
			&i.Contacts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersFirstPage = `-- name: GetUsersFirstPage :many
select id, name, email, registered_at, settings, contacts from "user"."user" order by "user".registered_at DESC, "user".id DESC LIMIT $1
`

func (q *Queries) GetUsersFirstPage(ctx context.Context, count int32) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersFirstPage, count)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.RegisteredAt,
			&i.Settings,
			&i.Contacts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
