// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: identity.sql

package storage

import (
	"context"

	uuid "github.com/gofrs/uuid"
)

const changePasswordStatus = `-- name: ChangePasswordStatus :exec
update "auth"."password"
set status = $1
where id = $2::uuid
`

type ChangePasswordStatusParams struct {
	Status PasswordStatus `db:"status" json:"status"`
	ID     uuid.UUID      `db:"id" json:"id"`
}

func (q *Queries) ChangePasswordStatus(ctx context.Context, arg ChangePasswordStatusParams) error {
	_, err := q.db.Exec(ctx, changePasswordStatus, arg.Status, arg.ID)
	return err
}

const createIdentity = `-- name: CreateIdentity :one
insert into "auth"."identity"
    (id, user_id, identity, type)
values ($1::uuid, $2::uuid, trim(lower($3::text)), $4)
RETURNING id, user_id, identity, type, status, created_at, updated_at
`

type CreateIdentityParams struct {
	ID       uuid.UUID    `db:"id" json:"id"`
	UserID   uuid.UUID    `db:"user_id" json:"userId"`
	Identity string       `db:"identity" json:"identity"`
	Type     IdentityType `db:"type" json:"type"`
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error) {
	row := q.db.QueryRow(ctx, createIdentity,
		arg.ID,
		arg.UserID,
		arg.Identity,
		arg.Type,
	)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Identity,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPassword = `-- name: CreatePassword :one
insert into "auth"."password"
    (id, user_id, password_hash)
values ($1::uuid, $2::uuid, $3::text)
RETURNING id, user_id, password_hash, status, created_at, updated_at
`

type CreatePasswordParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	UserID       uuid.UUID `db:"user_id" json:"userId"`
	PasswordHash string    `db:"password_hash" json:"passwordHash"`
}

func (q *Queries) CreatePassword(ctx context.Context, arg CreatePasswordParams) (Password, error) {
	row := q.db.QueryRow(ctx, createPassword, arg.ID, arg.UserID, arg.PasswordHash)
	var i Password
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIdentity = `-- name: DeleteIdentity :exec
delete from "auth"."identity"
where id = $1::uuid
`

func (q *Queries) DeleteIdentity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteIdentity, id)
	return err
}

const deletePassword = `-- name: DeletePassword :exec
delete from "auth"."password"
where id = $1::uuid
`

func (q *Queries) DeletePassword(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePassword, id)
	return err
}

const deleteUserIdentities = `-- name: DeleteUserIdentities :exec
DELETE FROM "auth"."identity"
WHERE user_id = $1::uuid
`

func (q *Queries) DeleteUserIdentities(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserIdentities, userID)
	return err
}

const deleteUserPasswords = `-- name: DeleteUserPasswords :exec
DELETE FROM "auth"."password"
WHERE user_id = $1::uuid
`

func (q *Queries) DeleteUserPasswords(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserPasswords, userID)
	return err
}

const selectIdentity = `-- name: SelectIdentity :one
select id, user_id, identity, type, status, created_at, updated_at
from "auth"."identity"
where identity = trim(lower($1::text))
`

func (q *Queries) SelectIdentity(ctx context.Context, identity string) (Identity, error) {
	row := q.db.QueryRow(ctx, selectIdentity, identity)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Identity,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectUserPasswords = `-- name: SelectUserPasswords :many
select id, user_id, password_hash, status, created_at, updated_at
from "auth"."password"
where user_id = $1::uuid
order by created_at desc
limit 2
`

func (q *Queries) SelectUserPasswords(ctx context.Context, userID uuid.UUID) ([]Password, error) {
	rows, err := q.db.Query(ctx, selectUserPasswords, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Password
	for rows.Next() {
		var i Password
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PasswordHash,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const verifyIdentity = `-- name: VerifyIdentity :one
UPDATE "auth"."identity"
SET status = 'verified'
WHERE id = $1::uuid
RETURNING id, user_id, identity, type, status, created_at, updated_at
`

func (q *Queries) VerifyIdentity(ctx context.Context, id uuid.UUID) (Identity, error) {
	row := q.db.QueryRow(ctx, verifyIdentity, id)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Identity,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
