// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: one_time_password.sql

package storage

import (
	"context"
	"database/sql"
	"time"

	uuid "github.com/gofrs/uuid"
)

const createOneTimePassword = `-- name: CreateOneTimePassword :one
INSERT INTO auth.one_time_password (token, email, user_id, used_at, expires_at, can_resend_at)
VALUES ($1, $2, $3, $4, $5, $6)
    ON CONFLICT (token) DO UPDATE
                               SET
                               user_id = EXCLUDED.user_id,
                               email = EXCLUDED.email,
                               used_at = EXCLUDED.used_at,
                               expires_at = EXCLUDED.expires_at,
                               can_resend_at = EXCLUDED.can_resend_at
                               RETURNING token, user_id, used_at, created_at, expires_at, email, can_resend_at
`

type CreateOneTimePasswordParams struct {
	Token       string        `db:"token" json:"token"`
	Email       string        `db:"email" json:"email"`
	UserID      uuid.NullUUID `db:"user_id" json:"userId"`
	UsedAt      sql.NullTime  `db:"used_at" json:"usedAt"`
	ExpiresAt   time.Time     `db:"expires_at" json:"expiresAt"`
	CanResendAt time.Time     `db:"can_resend_at" json:"canResendAt"`
}

func (q *Queries) CreateOneTimePassword(ctx context.Context, arg CreateOneTimePasswordParams) (OneTimePassword, error) {
	row := q.db.QueryRow(ctx, createOneTimePassword,
		arg.Token,
		arg.Email,
		arg.UserID,
		arg.UsedAt,
		arg.ExpiresAt,
		arg.CanResendAt,
	)
	var i OneTimePassword
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.UsedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Email,
		&i.CanResendAt,
	)
	return i, err
}

const deleteOneTimePasswordByEmail = `-- name: DeleteOneTimePasswordByEmail :exec
DELETE FROM "auth"."one_time_password"
WHERE email = $1
`

func (q *Queries) DeleteOneTimePasswordByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteOneTimePasswordByEmail, email)
	return err
}

const deleteOneTimePasswordByToken = `-- name: DeleteOneTimePasswordByToken :exec
DELETE
FROM auth.one_time_password
WHERE token = $1
`

func (q *Queries) DeleteOneTimePasswordByToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteOneTimePasswordByToken, token)
	return err
}

const getLastActiveOneTimePasswordByEmail = `-- name: GetLastActiveOneTimePasswordByEmail :one
SELECT token, user_id, used_at, created_at, expires_at, email, can_resend_at
FROM auth.one_time_password
WHERE
    email = $1
AND
    used_at is null
AND
    expires_at > NOW()
AND
    can_resend_at > NOW()
ORDER BY created_at desc
    LIMIT 1
`

func (q *Queries) GetLastActiveOneTimePasswordByEmail(ctx context.Context, email string) (OneTimePassword, error) {
	row := q.db.QueryRow(ctx, getLastActiveOneTimePasswordByEmail, email)
	var i OneTimePassword
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.UsedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Email,
		&i.CanResendAt,
	)
	return i, err
}

const getLastOneTimePassword = `-- name: GetLastOneTimePassword :one
SELECT token, user_id, used_at, created_at, expires_at, email, can_resend_at
FROM auth.one_time_password
ORDER BY created_at desc
LIMIT 1
`

func (q *Queries) GetLastOneTimePassword(ctx context.Context) (OneTimePassword, error) {
	row := q.db.QueryRow(ctx, getLastOneTimePassword)
	var i OneTimePassword
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.UsedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Email,
		&i.CanResendAt,
	)
	return i, err
}

const getOneTimePasswordByToken = `-- name: GetOneTimePasswordByToken :one
SELECT token, user_id, used_at, created_at, expires_at, email, can_resend_at
FROM auth.one_time_password
WHERE token = $1
`

func (q *Queries) GetOneTimePasswordByToken(ctx context.Context, token string) (OneTimePassword, error) {
	row := q.db.QueryRow(ctx, getOneTimePasswordByToken, token)
	var i OneTimePassword
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.UsedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Email,
		&i.CanResendAt,
	)
	return i, err
}

const setUsedOneTimePassword = `-- name: SetUsedOneTimePassword :one
UPDATE "auth"."one_time_password"
SET user_id = $1::uuid,
used_at = NOW()
WHERE token = $2
    RETURNING token, user_id, used_at, created_at, expires_at, email, can_resend_at
`

type SetUsedOneTimePasswordParams struct {
	UserID uuid.UUID `db:"user_id" json:"userId"`
	Token  string    `db:"token" json:"token"`
}

func (q *Queries) SetUsedOneTimePassword(ctx context.Context, arg SetUsedOneTimePasswordParams) (OneTimePassword, error) {
	row := q.db.QueryRow(ctx, setUsedOneTimePassword, arg.UserID, arg.Token)
	var i OneTimePassword
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.UsedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Email,
		&i.CanResendAt,
	)
	return i, err
}

const updateOneTimePasswordExpiresAt = `-- name: UpdateOneTimePasswordExpiresAt :one
UPDATE "auth"."one_time_password"
SET expires_at = $1::timestamptz
WHERE token = $2
    RETURNING token, user_id, used_at, created_at, expires_at, email, can_resend_at
`

type UpdateOneTimePasswordExpiresAtParams struct {
	ExpiresAt time.Time `db:"expires_at" json:"expiresAt"`
	Token     string    `db:"token" json:"token"`
}

func (q *Queries) UpdateOneTimePasswordExpiresAt(ctx context.Context, arg UpdateOneTimePasswordExpiresAtParams) (OneTimePassword, error) {
	row := q.db.QueryRow(ctx, updateOneTimePasswordExpiresAt, arg.ExpiresAt, arg.Token)
	var i OneTimePassword
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.UsedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Email,
		&i.CanResendAt,
	)
	return i, err
}
