// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: refresh_token.sql

package storage

import (
	"context"
	"time"

	uuid "github.com/gofrs/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO auth.refresh_token (hash, user_id, session_id, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING hash, session_id, user_id, status, created_at, expires_at
`

type CreateRefreshTokenParams struct {
	Hash      string    `db:"hash" json:"hash"`
	UserID    uuid.UUID `db:"user_id" json:"userId"`
	SessionID uuid.UUID `db:"session_id" json:"sessionId"`
	ExpiresAt time.Time `db:"expires_at" json:"expiresAt"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.Hash,
		arg.UserID,
		arg.SessionID,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.Hash,
		&i.SessionID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE
FROM auth.refresh_token
WHERE hash = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, hash string) error {
	_, err := q.db.Exec(ctx, deleteRefreshToken, hash)
	return err
}

const deleteRefreshTokensBySessionId = `-- name: DeleteRefreshTokensBySessionId :exec
DELETE
FROM auth.refresh_token
WHERE session_id = $1
`

func (q *Queries) DeleteRefreshTokensBySessionId(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokensBySessionId, sessionID)
	return err
}

const deleteRefreshTokensByUserId = `-- name: DeleteRefreshTokensByUserId :exec
DELETE
FROM auth.refresh_token
WHERE user_id = $1
`

func (q *Queries) DeleteRefreshTokensByUserId(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokensByUserId, userID)
	return err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT hash, session_id, user_id, status, created_at, expires_at
FROM auth.refresh_token
WHERE hash = $1
and status = 'active'
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, hash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, hash)
	var i RefreshToken
	err := row.Scan(
		&i.Hash,
		&i.SessionID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const revokeRefreshTokenBySessionId = `-- name: RevokeRefreshTokenBySessionId :one
UPDATE "auth"."refresh_token"
SET status = 'revoked'
WHERE session_id = $1
    RETURNING hash, session_id, user_id, status, created_at, expires_at
`

func (q *Queries) RevokeRefreshTokenBySessionId(ctx context.Context, sessionID uuid.UUID) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, revokeRefreshTokenBySessionId, sessionID)
	var i RefreshToken
	err := row.Scan(
		&i.Hash,
		&i.SessionID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateRefreshTokenExpiresAt = `-- name: UpdateRefreshTokenExpiresAt :one
UPDATE "auth"."refresh_token"
SET expires_at = $1
WHERE hash = $2
    RETURNING hash, session_id, user_id, status, created_at, expires_at
`

type UpdateRefreshTokenExpiresAtParams struct {
	ExpiresAt time.Time `db:"expires_at" json:"expiresAt"`
	Hash      string    `db:"hash" json:"hash"`
}

func (q *Queries) UpdateRefreshTokenExpiresAt(ctx context.Context, arg UpdateRefreshTokenExpiresAtParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, updateRefreshTokenExpiresAt, arg.ExpiresAt, arg.Hash)
	var i RefreshToken
	err := row.Scan(
		&i.Hash,
		&i.SessionID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateRefreshTokenUserId = `-- name: UpdateRefreshTokenUserId :one
UPDATE "auth"."refresh_token"
SET user_id = $1
WHERE hash = $2
    RETURNING hash, session_id, user_id, status, created_at, expires_at
`

type UpdateRefreshTokenUserIdParams struct {
	UserID uuid.UUID `db:"user_id" json:"userId"`
	Hash   string    `db:"hash" json:"hash"`
}

func (q *Queries) UpdateRefreshTokenUserId(ctx context.Context, arg UpdateRefreshTokenUserIdParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, updateRefreshTokenUserId, arg.UserID, arg.Hash)
	var i RefreshToken
	err := row.Scan(
		&i.Hash,
		&i.SessionID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
