// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: revoked_token.sql

package storage

import (
	"context"
	"time"
)

const createRevokedToken = `-- name: CreateRevokedToken :one
INSERT INTO auth.revoked_token (token_jti, expired)
VALUES ($1, $2)
    ON CONFLICT (token_jti) DO UPDATE
                               SET
                                   expired = EXCLUDED.expired
                               RETURNING token_jti, expired
`

type CreateRevokedTokenParams struct {
	TokenJti string    `db:"token_jti" json:"tokenJti"`
	Expired  time.Time `db:"expired" json:"expired"`
}

func (q *Queries) CreateRevokedToken(ctx context.Context, arg CreateRevokedTokenParams) (RevokedToken, error) {
	row := q.db.QueryRow(ctx, createRevokedToken, arg.TokenJti, arg.Expired)
	var i RevokedToken
	err := row.Scan(&i.TokenJti, &i.Expired)
	return i, err
}

const deleteExpiredRevokedTokens = `-- name: DeleteExpiredRevokedTokens :exec
DELETE
FROM auth.revoked_token
WHERE NOW() > expired
`

func (q *Queries) DeleteExpiredRevokedTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRevokedTokens)
	return err
}

const deleteRevokedToken = `-- name: DeleteRevokedToken :exec
DELETE
FROM auth.revoked_token
WHERE token_jti = $1
`

func (q *Queries) DeleteRevokedToken(ctx context.Context, tokenJti string) error {
	_, err := q.db.Exec(ctx, deleteRevokedToken, tokenJti)
	return err
}

const getRevokedTokenByJti = `-- name: GetRevokedTokenByJti :one
SELECT token_jti, expired
FROM auth.revoked_token
WHERE token_jti = $1
`

func (q *Queries) GetRevokedTokenByJti(ctx context.Context, tokenJti string) (RevokedToken, error) {
	row := q.db.QueryRow(ctx, getRevokedTokenByJti, tokenJti)
	var i RevokedToken
	err := row.Scan(&i.TokenJti, &i.Expired)
	return i, err
}
