// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_info.sql

package storage

import (
	"context"

	uuid "github.com/gofrs/uuid"
)

const deleteUserInfo = `-- name: DeleteUserInfo :exec
DELETE FROM "auth".user_info WHERE id = $1::uuid`

func (q *Queries) DeleteUserInfo(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserInfo, id)
	return err
}

const saveUserInfo = `-- name: SaveUserInfo :one
INSERT INTO "auth"."user_info" (id, name)
VALUES ($1::uuid, $2::text)
RETURNING id, name, created_at, updated_at`

type SaveUserInfoParams struct {
	ID   uuid.UUID `db:"id" json:"id"`
	Name string    `db:"name" json:"name"`
}

func (q *Queries) SaveUserInfo(ctx context.Context, arg SaveUserInfoParams) (UserInfo, error) {
	row := q.db.QueryRow(ctx, saveUserInfo, arg.ID, arg.Name)
	var i UserInfo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
