// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: verification_code.sql

package storage

import (
	"context"
	"database/sql"
	"time"

	uuid "github.com/gofrs/uuid"
	"github.com/jackc/pgtype"
)

const createVerificationCode = `-- name: CreateVerificationCode :one
INSERT INTO auth.verification_code (code, action, email, user_id, used_at, payload, expires_at, can_resend_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
    ON CONFLICT (code) DO UPDATE
                               SET
                              action = EXCLUDED.action,
                              email = EXCLUDED.email,
                              user_id = EXCLUDED.user_id,
                              used_at = EXCLUDED.used_at,
                              payload = EXCLUDED.payload,
                              expires_at = EXCLUDED.expires_at,
                              can_resend_at = EXCLUDED.can_resend_at
                               RETURNING code, action, email, user_id, used_at, payload, created_at, expires_at, can_resend_at
`

type CreateVerificationCodeParams struct {
	Code        string             `db:"code" json:"code"`
	Action      VerificationAction `db:"action" json:"action"`
	Email       string             `db:"email" json:"email"`
	UserID      uuid.NullUUID      `db:"user_id" json:"userId"`
	UsedAt      sql.NullTime       `db:"used_at" json:"usedAt"`
	Payload     pgtype.JSONB       `db:"payload" json:"payload"`
	ExpiresAt   time.Time          `db:"expires_at" json:"expiresAt"`
	CanResendAt time.Time          `db:"can_resend_at" json:"canResendAt"`
}

func (q *Queries) CreateVerificationCode(ctx context.Context, arg CreateVerificationCodeParams) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, createVerificationCode,
		arg.Code,
		arg.Action,
		arg.Email,
		arg.UserID,
		arg.UsedAt,
		arg.Payload,
		arg.ExpiresAt,
		arg.CanResendAt,
	)
	var i VerificationCode
	err := row.Scan(
		&i.Code,
		&i.Action,
		&i.Email,
		&i.UserID,
		&i.UsedAt,
		&i.Payload,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.CanResendAt,
	)
	return i, err
}

const deleteVerificationCode = `-- name: DeleteVerificationCode :exec
DELETE
FROM
    auth.verification_code
WHERE
    code = $1
`

func (q *Queries) DeleteVerificationCode(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, deleteVerificationCode, code)
	return err
}

const deleteVerificationCodeForConfirmDanaUser = `-- name: DeleteVerificationCodeForConfirmDanaUser :exec
DELETE
FROM auth.verification_code
WHERE
    payload ->> 'dana_user_id' = $1::text
`

func (q *Queries) DeleteVerificationCodeForConfirmDanaUser(ctx context.Context, danaUserID string) error {
	_, err := q.db.Exec(ctx, deleteVerificationCodeForConfirmDanaUser, danaUserID)
	return err
}

const deleteVerificationCodeForTransferNft = `-- name: DeleteVerificationCodeForTransferNft :exec
DELETE
FROM auth.verification_code
WHERE
        user_id = $1
  AND
        payload ->> 'nft_id' = $2::text
  AND
        payload ->> 'wallet_id' = $3::text
`

type DeleteVerificationCodeForTransferNftParams struct {
	UserID   uuid.NullUUID `db:"user_id" json:"userId"`
	NftID    string        `db:"nft_id" json:"nftId"`
	WalletID string        `db:"wallet_id" json:"walletId"`
}

func (q *Queries) DeleteVerificationCodeForTransferNft(ctx context.Context, arg DeleteVerificationCodeForTransferNftParams) error {
	_, err := q.db.Exec(ctx, deleteVerificationCodeForTransferNft, arg.UserID, arg.NftID, arg.WalletID)
	return err
}

const deleteVerificationCodeForTransferNftByAddress = `-- name: DeleteVerificationCodeForTransferNftByAddress :exec
DELETE
FROM auth.verification_code
WHERE
        user_id = $1
  AND
        payload ->> 'nft_id' = $2::text
  AND
    payload ->> 'to_address' = $3::text
`

type DeleteVerificationCodeForTransferNftByAddressParams struct {
	UserID    uuid.NullUUID `db:"user_id" json:"userId"`
	NftID     string        `db:"nft_id" json:"nftId"`
	ToAddress string        `db:"to_address" json:"toAddress"`
}

func (q *Queries) DeleteVerificationCodeForTransferNftByAddress(ctx context.Context, arg DeleteVerificationCodeForTransferNftByAddressParams) error {
	_, err := q.db.Exec(ctx, deleteVerificationCodeForTransferNftByAddress, arg.UserID, arg.NftID, arg.ToAddress)
	return err
}

const getLastActiveVerificationCodeByUserId = `-- name: GetLastActiveVerificationCodeByUserId :one
SELECT code, action, email, user_id, used_at, payload, created_at, expires_at, can_resend_at
FROM auth.verification_code
WHERE
    user_id = $1
AND
    used_at is null
AND
    expires_at > NOW()
AND
    can_resend_at > NOW()
ORDER BY created_at desc
LIMIT 1
`

func (q *Queries) GetLastActiveVerificationCodeByUserId(ctx context.Context, userID uuid.NullUUID) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, getLastActiveVerificationCodeByUserId, userID)
	var i VerificationCode
	err := row.Scan(
		&i.Code,
		&i.Action,
		&i.Email,
		&i.UserID,
		&i.UsedAt,
		&i.Payload,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.CanResendAt,
	)
	return i, err
}

const getLastActiveVerificationCodeForTransferNft = `-- name: GetLastActiveVerificationCodeForTransferNft :one
SELECT code, action, email, user_id, used_at, payload, created_at, expires_at, can_resend_at
FROM auth.verification_code
WHERE
    user_id = $1
  AND
    used_at is null
  AND
    expires_at > NOW()
  AND
    can_resend_at > NOW()
  AND
    payload ->> 'nft_id' = $2::text
  AND
    payload ->> 'wallet_id' = $3::text
LIMIT 1
`

type GetLastActiveVerificationCodeForTransferNftParams struct {
	UserID   uuid.NullUUID `db:"user_id" json:"userId"`
	NftID    string        `db:"nft_id" json:"nftId"`
	WalletID string        `db:"wallet_id" json:"walletId"`
}

func (q *Queries) GetLastActiveVerificationCodeForTransferNft(ctx context.Context, arg GetLastActiveVerificationCodeForTransferNftParams) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, getLastActiveVerificationCodeForTransferNft, arg.UserID, arg.NftID, arg.WalletID)
	var i VerificationCode
	err := row.Scan(
		&i.Code,
		&i.Action,
		&i.Email,
		&i.UserID,
		&i.UsedAt,
		&i.Payload,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.CanResendAt,
	)
	return i, err
}

const getLastActiveVerificationCodeForTransferNftByAddress = `-- name: GetLastActiveVerificationCodeForTransferNftByAddress :one
SELECT code, action, email, user_id, used_at, payload, created_at, expires_at, can_resend_at
FROM auth.verification_code
WHERE
        user_id = $1
  AND
    used_at is null
  AND
        expires_at > NOW()
  AND
        can_resend_at > NOW()
  AND
        payload ->> 'nft_id' = $2::text
  AND
    payload ->> 'to_address' = $3::text
    LIMIT 1
`

type GetLastActiveVerificationCodeForTransferNftByAddressParams struct {
	UserID    uuid.NullUUID `db:"user_id" json:"userId"`
	NftID     string        `db:"nft_id" json:"nftId"`
	ToAddress string        `db:"to_address" json:"toAddress"`
}

func (q *Queries) GetLastActiveVerificationCodeForTransferNftByAddress(ctx context.Context, arg GetLastActiveVerificationCodeForTransferNftByAddressParams) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, getLastActiveVerificationCodeForTransferNftByAddress, arg.UserID, arg.NftID, arg.ToAddress)
	var i VerificationCode
	err := row.Scan(
		&i.Code,
		&i.Action,
		&i.Email,
		&i.UserID,
		&i.UsedAt,
		&i.Payload,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.CanResendAt,
	)
	return i, err
}

const getLastVerificationCodeByAction = `-- name: GetLastVerificationCodeByAction :one
SELECT code, action, email, user_id, used_at, payload, created_at, expires_at, can_resend_at
FROM auth.verification_code
WHERE action = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLastVerificationCodeByAction(ctx context.Context, action VerificationAction) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, getLastVerificationCodeByAction, action)
	var i VerificationCode
	err := row.Scan(
		&i.Code,
		&i.Action,
		&i.Email,
		&i.UserID,
		&i.UsedAt,
		&i.Payload,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.CanResendAt,
	)
	return i, err
}

const getVerificationCodeByCodeAndAction = `-- name: GetVerificationCodeByCodeAndAction :one
SELECT code, action, email, user_id, used_at, payload, created_at, expires_at, can_resend_at
FROM auth.verification_code
WHERE
    code = $1
AND
    action = $2
`

type GetVerificationCodeByCodeAndActionParams struct {
	Code   string             `db:"code" json:"code"`
	Action VerificationAction `db:"action" json:"action"`
}

func (q *Queries) GetVerificationCodeByCodeAndAction(ctx context.Context, arg GetVerificationCodeByCodeAndActionParams) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, getVerificationCodeByCodeAndAction, arg.Code, arg.Action)
	var i VerificationCode
	err := row.Scan(
		&i.Code,
		&i.Action,
		&i.Email,
		&i.UserID,
		&i.UsedAt,
		&i.Payload,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.CanResendAt,
	)
	return i, err
}

const getVerificationCodeByDanaUserId = `-- name: GetVerificationCodeByDanaUserId :one
SELECT code, action, email, user_id, used_at, payload, created_at, expires_at, can_resend_at
FROM auth.verification_code
WHERE
    payload ->> 'dana_user_id' = $1::text
ORDER BY created_at desc
LIMIT 1
`

func (q *Queries) GetVerificationCodeByDanaUserId(ctx context.Context, danaUserID string) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, getVerificationCodeByDanaUserId, danaUserID)
	var i VerificationCode
	err := row.Scan(
		&i.Code,
		&i.Action,
		&i.Email,
		&i.UserID,
		&i.UsedAt,
		&i.Payload,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.CanResendAt,
	)
	return i, err
}

const setUsedVerificationCode = `-- name: SetUsedVerificationCode :one
UPDATE "auth"."verification_code"
SET user_id = $1::uuid,
used_at = NOW()
WHERE code = $2
    RETURNING code, action, email, user_id, used_at, payload, created_at, expires_at, can_resend_at
`

type SetUsedVerificationCodeParams struct {
	UserID uuid.UUID `db:"user_id" json:"userId"`
	Code   string    `db:"code" json:"code"`
}

func (q *Queries) SetUsedVerificationCode(ctx context.Context, arg SetUsedVerificationCodeParams) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, setUsedVerificationCode, arg.UserID, arg.Code)
	var i VerificationCode
	err := row.Scan(
		&i.Code,
		&i.Action,
		&i.Email,
		&i.UserID,
		&i.UsedAt,
		&i.Payload,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.CanResendAt,
	)
	return i, err
}

const updateVerificationCodeExpires = `-- name: UpdateVerificationCodeExpires :one
UPDATE "auth"."verification_code"
SET expires_at = $1::timestamptz
WHERE code = $2
    RETURNING code, action, email, user_id, used_at, payload, created_at, expires_at, can_resend_at
`

type UpdateVerificationCodeExpiresParams struct {
	ExpiresAt time.Time `db:"expires_at" json:"expiresAt"`
	Code      string    `db:"code" json:"code"`
}

func (q *Queries) UpdateVerificationCodeExpires(ctx context.Context, arg UpdateVerificationCodeExpiresParams) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, updateVerificationCodeExpires, arg.ExpiresAt, arg.Code)
	var i VerificationCode
	err := row.Scan(
		&i.Code,
		&i.Action,
		&i.Email,
		&i.UserID,
		&i.UsedAt,
		&i.Payload,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.CanResendAt,
	)
	return i, err
}
