package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	graphql2 "github.com/go-modulus/auth/graphql"
	"github.com/go-modulus/auth/providers/email/action"
	graphql1 "github.com/go-modulus/auth/providers/email/graphql"
	"github.com/go-modulus/demo/internal/graphql/model"
)

// EmailSignUp is the resolver for the emailSignUp field.
func (r *mutationResolver) EmailSignUp(ctx context.Context, input graphql1.EmailSignUpInput, userInfo model.UserInfo) (graphql2.TokenPair, error) {
	return r.authResolver.EmailSignUp(ctx, input, userInfo)
}

// EmailSignIn is the resolver for the emailSignIn field.
func (r *mutationResolver) EmailSignIn(ctx context.Context, input graphql1.EmailSignInInput) (graphql2.TokenPair, error) {
	return r.authResolver.EmailSignIn(ctx, input)
}

// RequestResetPassword is the resolver for the requestResetPassword field.
func (r *mutationResolver) RequestResetPassword(ctx context.Context, email string) (interface{}, error) {
	panic(fmt.Errorf("not implemented: RequestResetPassword - requestResetPassword"))
}

// ConfirmResetPassword is the resolver for the confirmResetPassword field.
func (r *mutationResolver) ConfirmResetPassword(ctx context.Context, input action.ConfirmResetPasswordInput) (interface{}, error) {
	panic(fmt.Errorf("not implemented: ConfirmResetPassword - confirmResetPassword"))
}

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, input action.ChangePasswordInput) (interface{}, error) {
	panic(fmt.Errorf("not implemented: ChangePassword - changePassword"))
}
