package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"demo/graph/model"

	"github.com/gofrs/uuid"
)

// SaveDraft is the resolver for the saveDraft field.
func (r *mutationResolver) SaveDraft(ctx context.Context, conversationID uuid.UUID, messageID *uuid.UUID, text *string) (model.SaveDraftResult, error) {
	return r.messengerResolver.SaveDraft(ctx, conversationID, messageID, text)
}

// RemoveDraft is the resolver for the removeDraft field.
func (r *mutationResolver) RemoveDraft(ctx context.Context, conversationID uuid.UUID) (model.RemoveDraftResult, error) {
	return r.messengerResolver.RemoveDraft(ctx, conversationID)
}
