package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"demo/graph/model"

	"github.com/gofrs/uuid"
)

// CreateMessage is the resolver for the createMessage field.
func (r *mutationResolver) CreateMessage(ctx context.Context, conversationID uuid.UUID, text *string) (model.CreateMessageResult, error) {
	return r.messengerResolver.CreateMessage(ctx, conversationID, text)
}

// EditMessage is the resolver for the editMessage field.
func (r *mutationResolver) EditMessage(ctx context.Context, messageID uuid.UUID, text *string) (model.EditMessageResult, error) {
	return r.messengerResolver.EditMessage(ctx, messageID, text)
}

// DeleteMessage is the resolver for the deleteMessage field.
func (r *mutationResolver) DeleteMessage(ctx context.Context, messageID uuid.UUID) (model.DeleteMessageResult, error) {
	return r.messengerResolver.DeleteMessage(ctx, messageID)
}

// Messages is the resolver for the messages field.
func (r *queryResolver) Messages(ctx context.Context, conversationID uuid.UUID, first int, after *string) (model.MessagesResult, error) {
	return r.messengerResolver.Messages(ctx, conversationID, first, after)
}
