// Code generated by sqlc-fixture plugin for SQLc. DO NOT EDIT.

package fixture

import (
	"context"
	"github.com/go-modulus/demo/internal/auth/storage"
	uuid "github.com/gofrs/uuid"
	"testing"
	"time"
)

type UserInfoFixture struct {
	entity storage.UserInfo
	db     storage.DBTX
}

func NewUserInfoFixture(db storage.DBTX, defaultEntity storage.UserInfo) *UserInfoFixture {
	return &UserInfoFixture{
		db:     db,
		entity: defaultEntity,
	}
}

func (f *UserInfoFixture) ID(iD uuid.UUID) *UserInfoFixture {
	c := f.clone()
	c.entity.ID = iD
	return c
}

func (f *UserInfoFixture) Name(name string) *UserInfoFixture {
	c := f.clone()
	c.entity.Name = name
	return c
}

func (f *UserInfoFixture) CreatedAt(createdAt time.Time) *UserInfoFixture {
	c := f.clone()
	c.entity.CreatedAt = createdAt
	return c
}

func (f *UserInfoFixture) UpdatedAt(updatedAt time.Time) *UserInfoFixture {
	c := f.clone()
	c.entity.UpdatedAt = updatedAt
	return c
}

func (f *UserInfoFixture) clone() *UserInfoFixture {
	return &UserInfoFixture{
		db:     f.db,
		entity: f.entity,
	}
}

func (f *UserInfoFixture) save(ctx context.Context) error {
	query := `INSERT INTO "auth"."user_info"
            ("id", "name", "created_at", "updated_at")
            VALUES ($1, $2, $3, $4)
            RETURNING "id", "name", "created_at", "updated_at"
        `
	row := f.db.QueryRow(ctx, query,
		f.entity.ID,
		f.entity.Name,
		f.entity.CreatedAt,
		f.entity.UpdatedAt,
	)
	err := row.Scan(
		&f.entity.ID,
		&f.entity.Name,
		&f.entity.CreatedAt,
		&f.entity.UpdatedAt,
	)
	return err
}

func (f *UserInfoFixture) GetEntity() storage.UserInfo {
	return f.entity
}

func (f *UserInfoFixture) Create(tb testing.TB) *UserInfoFixture {
	err := f.save(context.Background())
	if err != nil {
		tb.Fatalf("failed to create UserInfo: %v", err)
	}
	f.Cleanup(tb)
	c := f.clone()
	return c
}

// Cleanup calls testing.TB.Cleanup() function with providing a callback inside it.
// This callback will delete a record from the table by primary key when test will be finished.
func (f *UserInfoFixture) Cleanup(tb testing.TB) *UserInfoFixture {
	tb.Cleanup(
		func() {
			query := `DELETE FROM "auth"."user_info" WHERE id = $1`
			_, err := f.db.Exec(context.Background(), query, f.entity.ID)

			if err != nil {
				tb.Fatalf("failed to cleanup UserInfo: %v", err)
			}
		})

	return f
}

func (f *UserInfoFixture) PullUpdates(tb testing.TB) *UserInfoFixture {
	c := f.clone()
	ctx := context.Background()
	query := `SELECT "id", "name", "created_at", "updated_at" FROM "auth"."user_info" WHERE id = $1`
	row := f.db.QueryRow(ctx, query,
		c.entity.ID,
	)

	err := row.Scan(
		&c.entity.ID,
		&c.entity.Name,
		&c.entity.CreatedAt,
		&c.entity.UpdatedAt,
	)
	if err != nil {
		tb.Fatalf("failed to actualize data UserInfo: %v", err)
	}
	return c
}

func (f *UserInfoFixture) PushUpdates(tb testing.TB) *UserInfoFixture {
	c := f.clone()
	query := `
        UPDATE "auth"."user_info" SET 
            "name" = $2,
            "created_at" = $3,
            "updated_at" = $4
        WHERE "id" = $1
        `
	_, err := f.db.Exec(
		context.Background(),
		query,
		f.entity.ID,
		f.entity.Name,
		f.entity.CreatedAt,
		f.entity.UpdatedAt,
	)
	if err != nil {
		tb.Fatalf("failed to push the data UserInfo: %v", err)
	}
	return c
}
